Qwen/Qwen2.5-1.5B-Instruct:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 7
  lora_rank: 32
  lora_alpha: 40
  lora_dropout: 0.04
  target_modules:
    - v_proj
    - q_proj
    - down_proj
    - k_proj
    - o_proj
    - ffn
    - gate_proj
    - up_proj
